---
- name: Install MariaDB.
  hosts: slurmdbdservers
  become: true
  vars_files:
    - mariadb.yml
  roles:
    - role: bertvv.mariadb
      tags: bertvv.mariadb

- name: Install Slurm Cluster.
  hosts: all
  become: true
  vars_files:
    - slurm.yml
  roles:
    - role: galaxyproject.slurm
      tags: galaxyproject.slurm