all:
  hosts:
    mnode.prometech.co.jp:
    cnode01.prometech.co.jp:
    cnode02.prometech.co.jp:
  children:
    slurmservers:   # which will install slurmctld
      hosts:
        mnode.prometech.co.jp:
    slurmexechosts:
      hosts:  # which will install slurmd
        cnode01.prometech.co.jp:
        cnode02.prometech.co.jp:
    slurmdbdservers:  # which will install slurmdbd
      hosts:
        mnode.prometech.co.jp:
    nfsservers: # which will install nfs server.
      hosts:
        mnode.prometech.co.jp:
    nfsclients: # which will install nfs-client & mount nfs directory.
      hosts:
        cnode01.prometech.co.jp:
        cnode02.prometech.co.jp:
    ldapservers: # which will install 389 Directory Server
      hosts:
        mnode.prometech.co.jp:
    ntpservers: # which will install NTP Server.
      hosts:
        mnode.prometech.co.jp:
    ntpclients: # which will install NTP Clients.
      hosts:
        cnode01.prometech.co.jp:
        cnode02.prometech.co.jp:
    xrdp:   # which will install Xrdp & tiger-vnc environment, set default multi-user.target.
      hosts:
        mnode.prometech.co.jp:
