all:
  hosts:
    mnode.prometech.co.jp:
    cnode01.prometech.co.jp:
    cnode02.prometech.co.jp:
  children:
    slurmservers:   # which will install slurmctld
      hosts:
        mnode.prometech.co.jp:
    slurmexechosts:
      hosts:  # which will install slurmd
        cnode01.prometech.co.jp:
        cnode02.prometech.co.jp:
    slurmdbdservers:  # which will install slurmdbd
      hosts:
        mnode.prometech.co.jp:
    nfsservers: # which will install nfs server.
      hosts:
        mnode.prometech.co.jp:
    nfsclients: # which will install nfs-client & mount nfs directory.
      hosts:
        cnode01.prometech.co.jp:
        cnode02.prometech.co.jp:
    ldapservers:
      hosts:
        mnode.prometech.co.jp:
    ntpservers:
      hosts:
        mnode.prometech.co.jp:
    ntpclients:
      hosts:
        cnode01.prometech.co.jp:
        cnode02.prometech.co.jp:
