hosts_entries:
  - ip: 192.168.56.60
    name: mnode mnode.prometech.co.jp
  - ip: 192.168.56.61
    name: cnode01 cnode01.prometech.co.jp
  - ip: 192.168.56.62
    name: cnode02 cnode02.prometech.co.jp