# roles/389ds/defaults/main.yml
---
# instance.inf
general:
  defaults: 999999999
  full_machine_name: 19e0e7f1e422
  start: true
  strict_host_checking: false
slapd:
  instance_name: ldap1
  ldapi: /run/slapd-ldap1.socket
  port: 389
  root_password: "{SSHA}qElpX7cixJmXbeGZuXLDGitGx4GbLc9w"   # This hash pw is generated at https://projects.marsching.org/weave4j/util/genpassword.php
  secure_port: 636
  self_sign_cert: true
  self_sign_cert_valid_months: 24
backend_userroot:
  create_suffix_entry: true
  require_index: false
  sample_entries: no
  suffix: dc=prometech,dc=co,dc=jp
# /etc/openldap/ldap.conf
LDAP_BASE: dc=prometech,dc=co,dc=jp
LDAP_URI: ldaps://slurmmaster.local
TLS_CACERT: /etc/openldap/certs/ca.crt
TLS_REQCERT: never