---

- name: Check munge dir
  file:
    path: /etc/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory

- name: Generate a Munge key for the cluster in the slurm-master host
  ansible.builtin.command: "dd if=/dev/urandom of=/etc/munge/munge.key bs=1 count=1024"
  args:
    creates: /etc/munge/munge.key
  delegate_to: "{{ groups['slurmservers'][0] }}"
  notify: restart munge

- name: Set permissions for /etc/munge/munge.key in master
  ansible.builtin.file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400
  delegate_to: "{{ groups['slurmservers'][0] }}"

- name: Retrieve Munge key from slurm-master host
  ansible.builtin.slurp:
    src: "/etc/munge/munge.key"
  register: _slurm_munge_key
  delegate_to: "{{ groups['slurmservers'][0] }}"

- name: Write Munge key to every host in the cluster
  ansible.builtin.copy:
    content: "{{ _slurm_munge_key.content | b64decode }}"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: 0400
  notify:
    - restart munge